doctrine:
    dbal:
        driver: 'pdo_mysql'
        url: '%env(DATABASE_URL)%'
        server_version: '5.7'  # Change si nécessaire pour ta version de MySQL
        charset: utf8mb4

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
