security:
    # Providers pour la gestion des utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User  # La classe de l'entité
                property: email  # La propriété utilisée pour l'identification (ici email)

    # Configuration des hachages de mots de passe (utilisation de bcrypt)
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        # Firewall de la page de connexion
        login:
            pattern: ^/login
            security: false  # Pas de sécurité sur la page de login

        # Firewall principal
        main:
            # Utilisation de l'authentification par formulaire
            form_login:
                login_path: app_login  # URL de la page de connexion
                check_path: app_login  # URL de soumission du formulaire
                username_parameter: email  # Paramètre du nom d'utilisateur
                password_parameter: password  # Paramètre du mot de passe
                enable_csrf: true  # Activation de la protection CSRF pour le formulaire

            # Déconnexion
            logout:
                path: app_logout
                target: /

            # Gestion des utilisateurs anonymes : plus besoin de 'anonymous' ici
            stateless: false  # Si vous souhaitez utiliser des sessions (généralement ce sera le cas)

    # Configuration des règles d'accès aux pages
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/reservation, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Permet aux utilisateurs non authentifiés d'accéder à la page de login
